# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Ain_shams/RiscV/Syn/Risc/Risc.cache/wt [current_project]
set_property parent.project_path C:/Ain_shams/RiscV/Syn/Risc/Risc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Ain_shams/RiscV/Syn/Risc/Risc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Ain_shams/RiscV/Design/shared_pkg.sv
  C:/Ain_shams/RiscV/Design/alu_decoder.sv
  C:/Ain_shams/RiscV/Design/csr_defs.sv
  C:/Ain_shams/RiscV/Design/csr_file.sv
  C:/Ain_shams/RiscV/Design/data_memory.sv
  C:/Ain_shams/RiscV/Design/decode_stage.sv
  C:/Ain_shams/RiscV/Design/execute_stage.sv
  C:/Ain_shams/RiscV/Design/fetch_stage.sv
  C:/Ain_shams/RiscV/Design/flp_add_sub.sv
  C:/Ain_shams/RiscV/Design/flp_div.sv
  C:/Ain_shams/RiscV/Design/flp_mul.sv
  C:/Ain_shams/RiscV/Design/flp_sqrt.sv
  C:/Ain_shams/RiscV/Design/fp_reg_file.sv
  C:/Ain_shams/RiscV/Design/fpu_decoder.sv
  C:/Ain_shams/RiscV/Design/hazard_unit.sv
  C:/Ain_shams/RiscV/Design/lzc_wr.sv
  C:/Ain_shams/RiscV/Design/memory_stage.sv
  C:/Ain_shams/RiscV/Design/non_restoring_divider.sv
  C:/Ain_shams/RiscV/Design/opcode_decoder.sv
  C:/Ain_shams/RiscV/Design/pc_adder.sv
  C:/Ain_shams/RiscV/Design/risc_alu.sv
  C:/Ain_shams/RiscV/Design/risc_control_unit.sv
  C:/Ain_shams/RiscV/Design/risc_data_memory.sv
  C:/Ain_shams/RiscV/Design/risc_fpu.sv
  C:/Ain_shams/RiscV/Design/risc_instruction_memory.sv
  C:/Ain_shams/RiscV/Design/risc_mem.sv
  C:/Ain_shams/RiscV/Design/risc_mux2.sv
  C:/Ain_shams/RiscV/Design/risc_mux3.sv
  C:/Ain_shams/RiscV/Design/risc_mux4.sv
  C:/Ain_shams/RiscV/Design/risc_reg_file.sv
  C:/Ain_shams/RiscV/Design/wallace_tree.sv
  C:/Ain_shams/RiscV/Design/wb_stage.sv
  C:/Ain_shams/RiscV/Design/riscv_processor.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top riscv_processor -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_processor_utilization_synth.rpt -pb riscv_processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
